trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0  # Ensures full repository history

  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '11'
      jdkArchitecture: 'x64'
      jdkSource: 'PreInstalled'

  - script: |
      java -version
      echo "Java is installed"
    displayName: 'Verify Java Installation'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/target'
      Contents: 'spring-petclinic-*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
